# Data Mining

## Decision Tree (ID3)

### Import Library

In [7]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder

### Preparing the data

In [8]:
df_path = 'Data/News_dataset.csv'
df = pd.read_csv(df_path,sep=';')
df.head()

File_Name  \
0  Data/bbc\business\001.txt   
1  Data/bbc\business\002.txt   
2  Data/bbc\business\003.txt   
3  Data/bbc\business\004.txt   
4  Data/bbc\business\005.txt   

                                             Content  Category  
0  Ad sales boost Time Warner profit\n\nQuarterly...  business  
1  Dollar gains on Greenspan speech\n\nThe dollar...  business  
2  Yukos unit buyer faces loan claim\n\nThe owner...  business  
3  High fuel prices hit BA's profits\n\nBritish A...  business  
4  Pernod takeover talk lifts Domecq\n\nShares in...  business

In [9]:
train = df.copy()

### Preprocessing

*using label encoder*

In [10]:
encoder = LabelEncoder()

In [11]:
train.shape

(2225, 3)

In [12]:
length = train.shape[1]
col = train.columns
for i in range (length):
    print(i)
    a = encoder.fit_transform(train.iloc[:,i:i+1])
    a = pd.DataFrame(a, columns=[col[i]+'new'])
    train= train.join(a)

0
1
2


c:\users\user\appdata\local\programs\python\python37\lib\site-packages\sklearn\preprocessing\label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [13]:
train

File_Name  \
0     Data/bbc\business\001.txt   
1     Data/bbc\business\002.txt   
2     Data/bbc\business\003.txt   
3     Data/bbc\business\004.txt   
4     Data/bbc\business\005.txt   
...                         ...   
2220      Data/bbc\tech\397.txt   
2221      Data/bbc\tech\398.txt   
2222      Data/bbc\tech\399.txt   
2223      Data/bbc\tech\400.txt   
2224      Data/bbc\tech\401.txt   

                                                Content  Category  \
0     Ad sales boost Time Warner profit\n\nQuarterly...  business   
1     Dollar gains on Greenspan speech\n\nThe dollar...  business   
2     Yukos unit buyer faces loan claim\n\nThe owner...  business   
3     High fuel prices hit BA's profits\n\nBritish A...  business   
4     Pernod takeover talk lifts Domecq\n\nShares in...  business   
...                                                 ...       ...   
2220  BT program to beat dialler scams\n\nBT is intr...      tech   
2221  Spam e-mails tempt net shoppers\n\nComputer us...      tech   
2222  Be careful how you code\n\nA new European dire...      tech   
2223  US cyber security chief resigns\n\nThe man mak...      tech   
2224  Losing yourself in online gaming\n\nOnline rol...      tech   

      File_Namenew  Contentnew  Categorynew  
0                0          52            0  
1                1         550            0  
2                2        2123            0  
3                3         863            0  
4                4        1446            0  
...            ...         ...          ...  
2220          2220         138            4  
2221          2221        1702            4  
2222          2222         169            4  
2223          2223        1929            4  
2224          2224        1159            4  

[2225 rows x 6 columns]

In [14]:
test = train

### ID3 Algorithm

In [15]:
clf = DecisionTreeClassifier(
    criterion= "entropy"
)

clf_entropy = clf.fit(train.iloc[:,3:5], train.iloc[:,5])

In [16]:
clf_entropy

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [17]:
pred = clf_entropy.predict(test.iloc[:,3:5])
print("predicted values = ")
print(pred)

predicted values = 
[0 0 0 ... 4 4 4]


In [18]:
predict = []
for i in pred:
    if i == 0:
        predict.append("bussiness")
    elif i == 1:
        predict.append("entertainment")
    elif i == 2:
        predict.append("politics")
    elif i == 3:
        predict.append("sport")
    else :
        predict.append("tech")

In [19]:
predict

['bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'bussiness',
 'buss

In [20]:
result = test.iloc[:,0:3]

In [21]:
result['predict'] = predict

In [22]:
result

File_Name  \
0     Data/bbc\business\001.txt   
1     Data/bbc\business\002.txt   
2     Data/bbc\business\003.txt   
3     Data/bbc\business\004.txt   
4     Data/bbc\business\005.txt   
...                         ...   
2220      Data/bbc\tech\397.txt   
2221      Data/bbc\tech\398.txt   
2222      Data/bbc\tech\399.txt   
2223      Data/bbc\tech\400.txt   
2224      Data/bbc\tech\401.txt   

                                                Content  Category    predict  
0     Ad sales boost Time Warner profit\n\nQuarterly...  business  bussiness  
1     Dollar gains on Greenspan speech\n\nThe dollar...  business  bussiness  
2     Yukos unit buyer faces loan claim\n\nThe owner...  business  bussiness  
3     High fuel prices hit BA's profits\n\nBritish A...  business  bussiness  
4     Pernod takeover talk lifts Domecq\n\nShares in...  business  bussiness  
...                                                 ...       ...        ...  
2220  BT program to beat dialler scams\n\nBT is intr...      tech       tech  
2221  Spam e-mails tempt net shoppers\n\nComputer us...      tech       tech  
2222  Be careful how you code\n\nA new European dire...      tech       tech  
2223  US cyber security chief resigns\n\nThe man mak...      tech       tech  
2224  Losing yourself in online gaming\n\nOnline rol...      tech       tech  

[2225 rows x 4 columns]

### Evaluation

#### Confusion Matrix

In [23]:
conf_matrix = confusion_matrix(test.iloc[:,5], pred)
print("Confusion Matrix: ", conf_matrix) 
      
#     print ("Accuracy : ", 
#     accuracy_score(y_test,y_pred)*100) 
      
#     print("Report : ", 
#     classification_report(y_test, y_pred)) 

Confusion Matrix:  [[510   0   0   0   0]
 [  0 386   0   0   0]
 [  0   0 417   0   0]
 [  0   0   0 511   0]
 [  0   0   0   0 401]]


#### F-measure

In [24]:
precision = conf_matrix[0][0]/(conf_matrix[0][0]+conf_matrix[1][0])
recall = conf_matrix[0][0]/(conf_matrix[0][0]+conf_matrix[0][1])
fmeasure = (2*precision*recall)/(precision+recall)

In [25]:
print("Precision : ", precision)
print("recall : ", recall)
print("f-measure : ", fmeasure)

Precision :  1.0
recall :  1.0
f-measure :  1.0


#### Accuracy

In [26]:
acc = accuracy_score(test.iloc[:,5], pred)*100
print(acc,"%")

100.0 %


#### Report

In [27]:
print("report :")
print(classification_report(test.iloc[:,5], pred) )

report :
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       510
           1       1.00      1.00      1.00       386
           2       1.00      1.00      1.00       417
           3       1.00      1.00      1.00       511
           4       1.00      1.00      1.00       401

    accuracy                           1.00      2225
   macro avg       1.00      1.00      1.00      2225
weighted avg       1.00      1.00      1.00      2225

